services:
  - type: web
    name: casino-backend
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python3 -m uvicorn app:app --host 0.0.0.0 --port 10000
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.9
