# render.yaml
services:
  - type: web
    name: casino-backend
    env: docker
    plan: starter            # $7/月，不休眠
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false          # 去 Render 介面貼你的 External DB URL
      - key: SECRET_KEY
        generateValue: true
