services:
  - type: web
    name: casino-backend
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python3 -m uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: ADMIN_TOKEN
        sync: false
      - key: ALLOWED_ORIGINS
        value: "https://topz0705.com,https://casino-frontend-pya7.onrender.com,http://localhost:5173"
